pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "controllers", preload: true
pin "flowbite"
pin "modal"
pin "controllers/load_counties"
pin "controllers/load_sub_counties"
pin "controllers/load_counties_modal"
pin "requestDropdown"
pin "controllers/toggleFilter"
pin "dropdown"
pin "nested_forms"
pin "district"
pin "truncate"
pin "chartkick"
pin "Chart.bundle"
pin "users/filterUsers"
pin "users/userDropDown"
pin "controllers/filter_modal"
pin "dashboard"
pin "eventUser"
pin "eventTab"
pin "inventoryDonorType"
pin "scroll_to_top"